### ISSUE TITLE
Change to pymodbus v3.1.2 needed 

### ISSUE THREAD

**Issue by ArekKubacki** [wasilukm/hoymiles_modbus#11]
* hoymiles_modbus version: 0.5.0
* Python version: 3.10
* Operating System: Ubuntu

### Description

The latest version of Home Assistant requires pymodbus >3.1. Unfortunately, the library throws an error.
```
Traceback (most recent call last):
  File "/home/homeassistant/my_script.py", line 2, in <module>
    from hoymiles.client import HoymilesModbusTCP
  File "/home/homeassistant/hoymiles/client.py", line 5, in <module>
    from pymodbus.client.sync import ModbusTcpClient
ModuleNotFoundError: No module named 'pymodbus.client.sync'

```
### What I Did
After changing to the module from the latest version:
```
from pymodbus.client.sync import ModbusTcpClient
```
to
```
from pymodbus.client import ModbusTcpClient
```
Throws an error
```
Traceback (most recent call last):
  File "/home/homeassistant/my_script.py", line 51, in <module>
    plant_data = HoymilesModbusTCP('192.168.1.xxx', port=502,  microinverter_type=MicroinverterType.HM, unit_id=modbusID).plant_data
  File "/home/homeassistant/hoymiles/client.py", line 111, in plant_data
    microinverter_data = self.microinverter_data
  File "/home/homeassistant/hoymiles/client.py", line 88, in microinverter_data
    result = self._read_registers(client, start_address, 20, self._unit_id)
  File "/home/homeassistant/hoymiles/client.py", line 72, in _read_registers
    result = client.read_holding_registers(start_address, count, unit=unit_id)
  File "/home/homeassistant/.local/lib/python3.10/site-packages/pymodbus/client/mixin.py", line 105, in read_holding_registers
    pdu_reg_read.ReadHoldingRegistersRequest(address, count, slave, **kwargs)
TypeError: ReadHoldingRegistersRequest.__init__() got multiple values for argument 'unit'
```

**Comment by wasilukm** [comment]
@ArekKubacki are you able to check #12 ?

**Comment by ArekKubacki** [comment]
It is alive! I think you can do a file push :)
